### ISSUE TITLE
npm run dev出错

### ISSUE THREAD

**Issue by cn-tommy-lee** [54sword/react-starter#2]
Windows10
$ node -v8.9.3
$ npm -v5.7.1

<img width="483" alt="3c02a967823adaa5bf2e385640aff4c" src="https://user-images.githubusercontent.com/10909333/37269136-16c957be-2604-11e8-888d-c7fd41d5c4cd.png">
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\lzw\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.7.1
3 info using node@v8.9.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle react-starter@1.0.0~predev: react-starter@1.0.0
6 info lifecycle react-starter@1.0.0~dev: react-starter@1.0.0
7 verbose lifecycle react-starter@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle react-starter@1.0.0~dev: PATH: C:\Users\lzw\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\blog\react-starter\node_modules\.bin;C:\Users\lzw\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\lzw\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\dotnet;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Users\lzw\AppData\Local\Programs\Python\Python35;C:\Users\lzw\AppData\Local\Programs\Python\Python35\Scripts;C:\Users\lzw\AppData\Local\Microsoft\WindowsApps;C:\Users\lzw\AppData\Roaming\npm;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Users\lzw\AppData\Local\Programs\Python\Python35;C:\Users\lzw\AppData\Local\Programs\Python\Python35\Scripts;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle react-starter@1.0.0~dev: CWD: C:\blog\react-starter
10 silly lifecycle react-starter@1.0.0~dev: Args: [ '/d /s /c',
10 silly lifecycle   'NODE_ENV=development __NODE__=false BABEL_ENV=server webpack --progress --colors --config webpack.development.config.js && NODE_ENV=development __NODE__=true BABEL_ENV=server node src/server ' ]
11 silly lifecycle react-starter@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle react-starter@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: react-starter@1.0.0 dev: `NODE_ENV=development __NODE__=false BABEL_ENV=server webpack --progress --colors --config webpack.development.config.js && NODE_ENV=development __NODE__=true BABEL_ENV=server node src/server `
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\lzw\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\lzw\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid react-starter@1.0.0
15 verbose cwd C:\blog\react-starter
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lzw\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v8.9.3
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error react-starter@1.0.0 dev: `NODE_ENV=development __NODE__=false BABEL_ENV=server webpack --progress --colors --config webpack.development.config.js && NODE_ENV=development __NODE__=true BABEL_ENV=server node src/server `
22 error Exit status 1
23 error Failed at the react-starter@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by 54sword** [comment]
你好，windows 环境我没有测试过，会有一些问题。
如图，估计是windows环境设置环境变量，前面需要加set。

https://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-on-windows
